### ISSUE TITLE
Documentation describes wrong font

### ISSUE THREAD

**Issue by mattouille** [gopherworks/bawt#5]
## Expected Behavior

> The logos use Spinnaker as their font.

## Current Behavior

> The logos use Prosto One as their font.

## Possible Solution

Replace Prosto One with Spinnaker

## Steps to Reproduce

1. Go to https://gopherworks.github.io/bawt/press-kit/

## Context

An earlier version of this logo uses Prosto One as the font, however, since rebranding we use Spinnaker.

**Comment by j-wil** [comment]
@mattouille It looks like the logos already use Spinnaker. Do we want to convert to Presto One or is this already done? The t gives it away.  

![screenshot-vectr com-2018 11 25-15-44-45](https://user-images.githubusercontent.com/7523651/48985037-313d6500-f0c9-11e8-9ef4-8351430b70a2.png)

**Comment by mattouille** [comment]
The correct font is Spinnaker
